manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tominabox1
      url-base: https://github.com/tominabox1/
    - name: nicell
      url-base: https://github.com/Nicell/
  projects:
    - name: zmk
      remote: tominabox1
      revision: test_pwr
      import: app/west.yml
  self:
    path: config
