manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tominabox1
      url-base: https://github.com/tominabox1/
  projects:
    - name: zmk
      remote: tominabox1
      revision: working_hid2
      import: app/west.yml
  self:
    path: config
