manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tominabox1
      url-base: https://github.com/tominabox1/
  projects:
    - name: zmkfirmware
      remote: zmk
      revision: main
      import: app/west.yml
  self:
    path: config
