on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (QAZ)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-qaz
        with:
          args: 'build "-s zmk/app -b nice_nano -- -DSHIELD=qaz -DZMK_CONFIG=/github/workspace/config"'
      - name: QAZ Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 qaz_nice_nano.uf2
      - name: Archive (QAZ)
        uses: actions/upload-artifact@v2
        with:
          name: qaz
          path: qaz_nice_nano.uf2
      - name: West Build (Microdox-left)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-microdox-left
        with:
          args: 'build "-s zmk/app -b nice_nano -- -DSHIELD=microdox_left -DZMK_CONFIG=/github/workspace/config"'
      - name: Microdox_Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 microdox_left_nice_nano.uf2
      - name: Archive (Microdox_Left)
        uses: actions/upload-artifact@v2
        with:
          name: microdox_left
          path: microdox_left_nice_nano.uf2
      - name: West Build (Microdox-right)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-microdox-right
        with:
          args: 'build "-s zmk/app -b nice_nano -- -DSHIELD=microdox_right -DZMK_CONFIG=/github/workspace/config"'
      - name: Microdox_Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 microdox_right_nice_nano.uf2
      - name: Archive (Microdox_Right)
        uses: actions/upload-artifact@v2
        with:
          name: microdox_right
          path: microdox_right_nice_nano.uf2